In [66]:
import numpy as np
import time

N = 10

start = time.time()
v_state = []

for i in range(2**N):
    vi = bin(2**N - i - 1).split('b')[1].replace("1", "1 ").replace("0", "-1 ").split()
    vi += [-1]*(N - len(vi))
    vi = np.array(vi, dtype="int32")
    v_state.append(vi)

print(time.time() - start)

0.005980491638183594


In [34]:
for i in range(2**N):
    vi = bin(i).split('b')[1].replace('1', '1 ').replace('0', '-1 ').split()
    vi.reverse()
    while len(vi) < N:
        vi.append(-1)
    vi.reverse()
    print(vi)

[-1, '-1']
[-1, '1']
['1', '-1']
['1', '1']


In [68]:
print(np.zeros((2, 2)))

[[0. 0.]
 [0. 0.]]


In [3]:
import numpy as np

i = np.identity(1)
np.kron(i, [[0, 1], [1, 0]])

array([[0., 1.],
       [1., 0.]])

In [80]:
import QBM

model = QBM.model(2, 100)
print(model.minimize_fun())

      fun: 1.3791187138672285e-17
 hess_inv: array([[1]])
      jac: array([2.23284587e-08])
  message: 'Optimization terminated successfully.'
     nfev: 6
      nit: 1
     njev: 3
   status: 0
  success: True
        x: array([3.71364876e-09])


In [8]:
a = np.array([[1,2], 
    [3,4]])

print(np.dot(a, a), np.inner(a, a.T), sep="\n")

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
